version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      PORT: 7070
      EMAIL_USER: youremail@gmail.com
      EMAIL_PASS: your-email-or-app-password
    ports:
      - "7070:7070"
    depends_on:
      - db

volumes:
  db_data:
