version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    environment:
      PORT: 7070
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
      EMAIL_USER: andhraw46@gmail.com        # Replace with your Gmail
      EMAIL_PASS: andhrawala4641          # Use Gmail app password if 2FA enabled
    ports:
      - "7070:7070"
    depends_on:
      - db

volumes:
  db_data:
